---
# handlers file for jenkins
- name: "Jenkins restart"
  service:
    name: jenkins
    state: restarted

- name: "Jenkins soft restart"
  shell: java -jar {{jenkins_cli}} -s {{jenkins_url}}/ safe-restart --username {{ jenkins_admin_username }} --password {{ jenkins_admin_password }}

- name: "Nginx restart"
  service:
    name: nginx
    state: restarted
