---
- name: "Configure Grafana"
  template:
    src: "grafana.ini.j2"
    dest: "/etc/grafana/grafana.ini"
  notify: "Restart grafana"

- name: "Grafana Service started"
  service:
    name: "grafana-server"
    state: "started"

- name: "Enable prometheus service"
  systemd:
    name: grafana-server
    daemon_reload: yes
    state: started
    enabled: yes
