---
- import_tasks: preflight.yml
- import_tasks: install.yml
- import_tasks: configure.yml

- name: "Ensure prometheus service is started and enabled"
  systemd:
    daemon_reload: true
    name: prometheus
    state: started
    enabled: true
