---
- name: "Add PostgreSQL key"
  apt_key:
    url: "https://www.postgresql.org/media/keys/ACCC4CF8.asc"
    state: present

- name: "Add PostgreSQL repository"
  apt_repository:
    repo: "deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main"
    filename: 'PostgreSQL'
    state: present
    update_cache: yes

- name: "Install PostgreSQL"
  apt:
    name: "{{ item }}"
    state: "present"
  with_items:
    - "postgresql-{{ postgres_server_version }}"
    - python-psycopg2
    - python3-psycopg2
    - libpq-dev

- name: "PostgreSQL Service started"
  service:
    name: "postgresql"
    state: "started"
